version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build(npm)'
    groups:
      tailwindcss:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      zag-js:
        patterns:
          - '@zag-js/*'
      react-aria:
        patterns:
          - '@react-aria/*'
          - '@react-stately/*'
      testing:
        patterns:
          - '@testing-library/*'
          - '@testing-library'
          - 'vitest'
          - '@vitest/*'
          - '@vitest'
          - '@playwright/*'
          - '@playwright'
      storybook:
        patterns:
          - '@storybook/*'
          - '*storybook*'
      vite:
        patterns:
          - 'vite'
          - '@vitejs/*'
          - '*vite*'
